### ISSUE TITLE
Some timezone data is still not updated properly

### ISSUE THREAD

**Issue by thisisamirmaleki** [Xosrov/Android-Timezone-Fix#2] opened 2023-06-08 20:09 UTC
Thanks for your straightforward module. I'm using it on ArrowOS13.1 and it does the job on most cases.

However, I came across an issue while using your module. The time's alright, but the DATE on the status bar is not correct from 23 to 24 everyday.
It might also be worth noting that the time widget is showing the wrong TIME too.

**Comment by Xosrov** [comment] 2023-06-09 04:39
I can confirm this is an issue, I'll look into it when I have the time. If you come across any additional info about this please share.

**Comment by Xosrov** [comment] 2023-06-10 08:32
@thisisamirmaleki 
Try out the new version from the dev branch: [Android-Timezone-Fix.zip](https://github.com/Xosrov/Android-Timezone-Fix/files/11711991/Android-Timezone-Fix.zip).  
Some files were missing and I added them. I haven't fully tested it so let me know if there are still problems.

**Comment by thisisamirmaleki** [comment] 2023-06-10 09:06
Thanks, the time widget is fixed now.
We need to wait for 23:00 in order to examine the date!

**Comment by Xosrov** [comment] 2023-06-11 05:51
@thisisamirmaleki If the problem is fixed, please close the issue and I'll merge and upload a new release. Thanks!

**Closed** 2023-06-12 17:21 UTC
Labels: bug

**Comment by thisisamirmaleki** [comment] 2023-06-12 19:37
I didn't have time and wasn't reminded to check it. It is now verified that the problem is no longer present. Thanks again.
